include::Title.adoc[lines=1..8]

[.text-center]
Отчет по лабороторной работе №1 +
на тему "Запуск программного обеспечения на микроконтроллере"

include::Title.adoc[lines=12..24]


== Запуск программного обеспечения на микроконтроллере

Задание: Описать процесс запуска программного обеспечения на микроконтроллер, описать указатель стека, счетчик программы, как происходит инициализация переменных нулевыми и не нулевыми значениями и запуск функции main.

Сразу после подачи питания происходит инициализация указателя стека на конечный адрес стека. Стек нужен для хранения локальных переменных, переходов функций, контекст прерываний, т.е. для оперативного сохранения временных значений. Указатель стека указывает на последний байт последнего элемента, добавленного в стек и хранится в регистрах процессора.

Инициализация переменных в нулевые значения. После подачи питания на микроконтроллер,регистр адреса команды указывает на 0 адрес, микроконтроллер начинает работу с начального адреса в нашем случае это 0х08000000. По этому адресу, находится таблица векторов прерывания, по начальному вектору находится команда инициализации указателя стека на конечный адрес стека и далее перехода на функцию инициализации.

После этого вызывается функция main().

== Ответы на вопросы по теме

1) Дайте определение понятию "Интегрированная среда разработки".

Ответ: Интегрированная среда разработки (IDE) – комплекс программных средств, используемый программистами для разработки программного обеспечения.

2) Что такое компилятор и чем он отличается от транслятора?

Ответ: Компилятор – это программа, которая осуществляет перевод исходной программы в эквивалентную ей объектную программу на языке машинных команд или языке ассемблера. Компилятор отличается от транслятора тем, что его результирующая программа написана обязательно на языке машинных команд или языке ассемблера.

3) Что такое компоновщик и какие функции он выполняет?

Ответ: Компоновщик — инструментальная программа, которая производит компоновку: принимает на вход один или несколько объектных модулей и собирает из них исполняемый или библиотечный файл-модуль.

4) Почему важен процесс проектирования ПО какие задачи входят в этот процесс?

Ответ: проектирование ПО важно, потому что оно позволяет оценить затрачиваемые на это ресурсы до начала создания и позволяет избежать разногласий между заказчиком и исполнителем. В процесс проектирования входят: выбор описания и архитектуры программы; составление ТЗ; определение схемы взаимодействия компонентов; утверждение ТЗ.

6) Зачем нужна отладка и в каких случаях она применяется? Для чего применяются точки остановки?

Ответ: Отладчик — это программный инструмент, позволяющий программисту наблюдать за выполнением исследуемой программы, останавливать и перезапускать её, прогонять в замедленном темпе, изменять значения в памяти. Для устранения ошибок в приложении.

Точки остановки устанавливаются везде, где нужно приостановить выполнение отладчика. Например, для просмотра состояния переменных кода или стек вызовов в определенной точке останова.

7) Какие еще важные IAR workbench можно добавить в таблицу карактеристик IAR.

Ответ: C-SPY отладчик предупреждает о переполнении стека. Менеджер проектов, облегчает контроль и управление рабочими модулями.
