:toc: macro 

include::Title.adoc[]

== Оглавление

toc::[]

== Введение

Цель: Разобрать типы данных С++, описать новые знания полученные из лекции 2.

Типы данных C++ — язык со статической типизацией. У каждой переменной на этапе компиляции должен быть чётко определённый тип данных.



.Встроенные типы С++
[cols="2,1,7"]
|=====================
|Тип | Длина |Комментарий
|*bool*| 1| Представляет значения, которые могут быть или *true*, или *false*.
|*char*|1	| Используется для символов ASCII в старых строках в стиле C или в объектах std::string,
которые никогда не будут преобразовываться в Юникод.
|*unsigned char*| 1 |	Аналог байта. В С++17 стандарте появился тип std::byte
|*int*|	4 |Целочисленное значение. Выбор по умолчанию для целых чисел
|*unsigned int*| 4| Беззнаковое целое число
|*float*| 4	|Число с плавающей точкой, поддерживается аппаратно некоторыми микроконтроллерами
|*double*| 8	|Число с плавающей запятой двойной точности. Выбор по умолчанию для значений с плавающей
точкой
|=====================

== Пользовательские типы и псевдонимы типов

Можно определить собственный тип. Структура и классы, опеределенные пользователем, являются личным типом данных пользователя.

Также можно вводить псевдонимы (alias), которые нужны для более понятной работы с типом.
Для этого используют ключевое слово using.

Определяем кортеж из 4 элементов разного типа.
Кортеж может хранить значения разных типов.

Далее двумя возможными способами объявляем псевдоним типа. 

В первом случае тип выводится компилятором. 
.main.cpp
[source, cpp]
----
using tMytype = decltype(t);
----

Во втором случае тип указываем напрямую.
.main.cpp
[source, cpp]
----
using tShortType = std::tuple<int, string, double, tU32>;
----

Объявляем функцию, принимающую аргумент типа, который имеет кортеж.
Объявляем псевдоним типа unsigned int.
Определяем переменную типа unsigned int.

Пример использования псевдонима.
.main.cpp
[source, cpp]
----
auto t = std::make_tuple(23, "AC/DC", 3.14, 4U);
using tMytype = decltype(t);

void myfunction(tMyType & value) {    
  ...
}

int main() 
{
  using tU32 = unsigned int;  
  tU32 i = 10U;               

  myfunction(t);           
}
----

== Литералы, неявное и явное преобразование типов

Литерал — это элемент программы, который непосредственно представляет значение.

Литералы целых типов можно записать в десятичном, восьмеричном и шестнадцатеричном виде. Вот как выглядит число 123, представленное десятичным, восьмеричным и шестнадцатеричным литералами: 123, 0173, 0х007В.

Буква U (или u) в конце определяет литерал как unsigned int, а две буквы – UL или LU – как тип unsigned long. Например: 12U, 13u, 1024UL.

Для явного указания типа float нужно использовать суффикс F или f, а для long double - L или l, но только в случае записи с десятичной точкой. Например: 3.14159F; 0/1f; 12.345L; 3el; 1.0E-3E; 1.0L.

Если мы инициализируем переменную типом float присваивая к ней дробное число, то будет происходить неявное преобразования из double в float, по этой причине теряется точность.

Нужно использовать явное преобразование типа, для того чтобы компилятор не сделал неожиданные преобразования.

Вместо этого, лучше указать компилятору явное преобразование из одного типа в другой. В этом случае, вы говорите компилятору, что я понимаю, что я делаю, это именно так и задумано.

Для преобразований из одного типа используют 4 вариантов преобразования:

* static_cast;
* const_cast;
* reinterpret_cast;
* dynamic_cast.

В лекции было рассмотренно 2 варианта преобразования static_cast и reinterpret_cast.

=== static_cast

static_cast позволяет сделать приведение близких типов (целые, пользовательских типов которые могут создаваться из типов который приводится, и указатель на void*) к указателю на любой тип.

Проверка производится на уровне компиляции, так что в случае ошибки сообщение будет получено в момент сборки приложения или библиотеки.

.main.cpp
[source, cpp]
----
int a = static_cast<int>(0); # (1)

int a = static_cast<int>(3.14);  # (2)

bool a = static_cast<bool>(-4);  # (3)

bool a  = static_cast<bool>(0);  # (4)

float f = 3.14f ;     # (5)

float f = static_cast<float>(3.14) ;  # (6)

Complex f = static_cast<3.14> #(7)
----


. Явно говорим, что 0 должен восприниматься как тип (int), хотя он и так является литералом типа int;

. Явно говорим, что 3.14 воспринимать как int, т.е взять только целую часть;

. Явно говорим, -4 нужно воспринять как bool тип, в данном случае true;

. Явно говорим, 0 нужно воспринять как bool тип, в данном случае false;

. Явно говорим, что 3.14 это float;

. Явно говорим, что 3.14 это float;

. Комплексное число может создаться из double, поэтому тут будет работать static_cast.

=== reinterpret_cast

reinterpret_cast преобразует типы, несовместимыми друг с другом, и используется для:

* В свой собственный тип;

* Указателя в интегральный тип;

* Интегрального типа в указатель;

* Указателя одного типа в указатель другого типа;

* Указателя на функцию одного типа в указатель на функцию другого типа;

.main.cpp
[source, cpp]
----
auto ptr = reinterpret_cast<volatile uint32_t *>(0x40010000) ; # (1)
auto value = *ptr ; #(2)
----

. Преобразует адрес 0x40010000 в указатель типа volatile uint32_t;

. Записывает в переменную value (типа) значение лежащее по указателю ptr, указывающего на адрес 0x40010000.

== Заключение 

В ходе данной практической работы были изучены типы данных С++. Для правильного указания типов переменной нужно использовать псевдонимы типа, вместо прямых типов, либо литералы или явное преобразование типов.